# Generated by Django 3.0.3 on 2020-02-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
